name: Test Windows project creation & build

on: [push]

jobs:
  create_and_build:

    name: Create and build

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node bin/create-cubing-app my-cubing-project
      - run: cd my-cubing-project && npm run build
